spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        techforum-in:
          destination: techforum-topic
          contentType: application/json
        techforum-out:
          destination: techforum-topic
          contentType: application/json